version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=erpuser
      - POSTGRES_PASSWORD=erppassword
      - POSTGRES_DB=erpdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=erpuser
      - DB_PASSWORD=erppassword
      - DB_NAME=erpdb
      - JWT_SECRET=your_jwt_secret
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
