version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-erp_db}
      MYSQL_USER: ${MYSQL_USER:-erp_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-erp_password}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
